name = "C-Tech"
author = "soundgoodizerfan"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dedd2e02e95c15e798455f8c4df48bd78855d4ed43daaaa4afca6868f9db9e37"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
