name = "C-Tech"
author = "soundgoodizerfan"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b338432ae980fb030f790ac64aedc5fa7c466f3ddee739934d6da1b7cf32be78"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
