name = "C-Tech"
author = "soundgoodizerfan"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b61524df4e147c49d743751ec1fdc5531d32ba5e5589b78706bcbe54190aea41"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
