name = "C-Tech"
author = "soundgoodizerfan"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93882402921cd96c36684521a931dff017fe6144b56356062928c91e19d59227"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
