name = "C-Tech"
author = "soundgoodizerfan"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36b59bd8f45af13894280527775f906acd4e4ab7b8586b0425bb580904657ea0"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
