name = "C-Tech"
author = "soundgoodizerfan"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6f149d68dcecf8e2d35071c8e3b8bf12ca5ee248d02ec9d66d3ff9442b615c8"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
